// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteV1AdminUsersByIdSessionsData, DeleteV1AdminUsersByIdSessionsResponses, DeleteV1EnvVarsByNameData, DeleteV1EnvVarsByNameResponses, DeleteV1SessionsByIdData, DeleteV1SessionsByIdResponses, DeleteV1TemplatesByIdData, DeleteV1TemplatesByIdResponses, DeleteV1TokensByIdData, DeleteV1TokensByIdResponses, DeleteV1WebhooksByIdData, DeleteV1WebhooksByIdResponses, DeleteV1WorkspacesByIdData, DeleteV1WorkspacesByIdResponses, GetAuthMeData, GetAuthMeResponses, GetAuthOidcStartData, GetAuthOidcStartResponses, GetHealthData, GetHealthResponses, GetReadyData, GetReadyResponses, GetV1AdminAuditLogsData, GetV1AdminAuditLogsResponses, GetV1AdminUsersData, GetV1AdminUsersResponses, GetV1EnvVarsData, GetV1EnvVarsResponses, GetV1SessionsData, GetV1SessionsResponses, GetV1TemplatesData, GetV1TemplatesResponses, GetV1TokensData, GetV1TokensResponses, GetV1WebhooksData, GetV1WebhooksResponses, GetV1WorkspacesByIdGitStatusData, GetV1WorkspacesByIdGitStatusResponses, GetV1WorkspacesData, GetV1WorkspacesResponses, PostAuthLoginData, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthTotpSetupData, PostAuthTotpSetupResponses, PostAuthTotpVerifyData, PostAuthTotpVerifyResponses, PostV1AdminUsersData, PostV1AdminUsersResponses, PostV1EnvVarsData, PostV1EnvVarsResponses, PostV1SessionsData, PostV1SessionsResponses, PostV1TemplatesData, PostV1TemplatesResponses, PostV1TokensData, PostV1TokensResponses, PostV1WebhooksData, PostV1WebhooksResponses, PostV1WorkspacesData, PostV1WorkspacesResponses, PutV1AdminUsersByIdRoleData, PutV1AdminUsersByIdRoleResponses, PutV1TemplatesByIdData, PutV1TemplatesByIdResponses, PutV1WebhooksByIdData, PutV1WebhooksByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Liveness probe
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/health',
    ...options
});

/**
 * Readiness probe
 */
export const getReady = <ThrowOnError extends boolean = false>(options?: Options<GetReadyData, ThrowOnError>) => (options?.client ?? client).get<GetReadyResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/ready',
    ...options
});

/**
 * Local authentication
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLoginData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLoginResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/auth/login',
    ...options
});

/**
 * Destroy session
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

/**
 * Get current user from session
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetAuthMeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/auth/me',
    ...options
});

/**
 * Start OIDC flow
 */
export const getAuthOidcStart = <ThrowOnError extends boolean = false>(options?: Options<GetAuthOidcStartData, ThrowOnError>) => (options?.client ?? client).get<GetAuthOidcStartResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/auth/oidc/start',
    ...options
});

/**
 * Generate TOTP secret for 2FA setup
 */
export const postAuthTotpSetup = <ThrowOnError extends boolean = false>(options?: Options<PostAuthTotpSetupData, ThrowOnError>) => (options?.client ?? client).post<PostAuthTotpSetupResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/auth/totp/setup',
    ...options
});

/**
 * Verify TOTP code and enable 2FA
 */
export const postAuthTotpVerify = <ThrowOnError extends boolean = false>(options: Options<PostAuthTotpVerifyData, ThrowOnError>) => (options.client ?? client).post<PostAuthTotpVerifyResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/auth/totp/verify',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List user sessions
 */
export const getV1Sessions = <ThrowOnError extends boolean = false>(options?: Options<GetV1SessionsData, ThrowOnError>) => (options?.client ?? client).get<GetV1SessionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/sessions',
    ...options
});

/**
 * Create terminal session
 */
export const postV1Sessions = <ThrowOnError extends boolean = false>(options?: Options<PostV1SessionsData, ThrowOnError>) => (options?.client ?? client).post<PostV1SessionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/sessions',
    ...options
});

/**
 * Delete session
 */
export const deleteV1SessionsById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1SessionsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1SessionsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/sessions/{id}',
    ...options
});

/**
 * List workspaces
 */
export const getV1Workspaces = <ThrowOnError extends boolean = false>(options?: Options<GetV1WorkspacesData, ThrowOnError>) => (options?.client ?? client).get<GetV1WorkspacesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/workspaces',
    ...options
});

/**
 * Create workspace
 */
export const postV1Workspaces = <ThrowOnError extends boolean = false>(options?: Options<PostV1WorkspacesData, ThrowOnError>) => (options?.client ?? client).post<PostV1WorkspacesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/workspaces',
    ...options
});

/**
 * Get git status for workspace
 */
export const getV1WorkspacesByIdGitStatus = <ThrowOnError extends boolean = false>(options: Options<GetV1WorkspacesByIdGitStatusData, ThrowOnError>) => (options.client ?? client).get<GetV1WorkspacesByIdGitStatusResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/workspaces/{id}/git-status',
    ...options
});

/**
 * Delete workspace
 */
export const deleteV1WorkspacesById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1WorkspacesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1WorkspacesByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/workspaces/{id}',
    ...options
});

/**
 * List all users (ADMIN only)
 */
export const getV1AdminUsers = <ThrowOnError extends boolean = false>(options?: Options<GetV1AdminUsersData, ThrowOnError>) => (options?.client ?? client).get<GetV1AdminUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/admin/users',
    ...options
});

/**
 * Create user (ADMIN only)
 */
export const postV1AdminUsers = <ThrowOnError extends boolean = false>(options?: Options<PostV1AdminUsersData, ThrowOnError>) => (options?.client ?? client).post<PostV1AdminUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/admin/users',
    ...options
});

/**
 * Update user role (ADMIN only)
 */
export const putV1AdminUsersByIdRole = <ThrowOnError extends boolean = false>(options: Options<PutV1AdminUsersByIdRoleData, ThrowOnError>) => (options.client ?? client).put<PutV1AdminUsersByIdRoleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/admin/users/{id}/role',
    ...options
});

/**
 * List audit logs (ADMIN only)
 */
export const getV1AdminAuditLogs = <ThrowOnError extends boolean = false>(options?: Options<GetV1AdminAuditLogsData, ThrowOnError>) => (options?.client ?? client).get<GetV1AdminAuditLogsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/admin/audit-logs',
    ...options
});

/**
 * Force-logout user - revoke all sessions (ADMIN only)
 */
export const deleteV1AdminUsersByIdSessions = <ThrowOnError extends boolean = false>(options: Options<DeleteV1AdminUsersByIdSessionsData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1AdminUsersByIdSessionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/admin/users/{id}/sessions',
    ...options
});

/**
 * List user webhooks
 */
export const getV1Webhooks = <ThrowOnError extends boolean = false>(options?: Options<GetV1WebhooksData, ThrowOnError>) => (options?.client ?? client).get<GetV1WebhooksResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/webhooks',
    ...options
});

/**
 * Create webhook
 */
export const postV1Webhooks = <ThrowOnError extends boolean = false>(options?: Options<PostV1WebhooksData, ThrowOnError>) => (options?.client ?? client).post<PostV1WebhooksResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/webhooks',
    ...options
});

/**
 * Delete webhook
 */
export const deleteV1WebhooksById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1WebhooksByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1WebhooksByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/webhooks/{id}',
    ...options
});

/**
 * Update webhook
 */
export const putV1WebhooksById = <ThrowOnError extends boolean = false>(options: Options<PutV1WebhooksByIdData, ThrowOnError>) => (options.client ?? client).put<PutV1WebhooksByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/webhooks/{id}',
    ...options
});

/**
 * List API tokens
 */
export const getV1Tokens = <ThrowOnError extends boolean = false>(options?: Options<GetV1TokensData, ThrowOnError>) => (options?.client ?? client).get<GetV1TokensResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/tokens',
    ...options
});

/**
 * Create API token
 */
export const postV1Tokens = <ThrowOnError extends boolean = false>(options?: Options<PostV1TokensData, ThrowOnError>) => (options?.client ?? client).post<PostV1TokensResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/tokens',
    ...options
});

/**
 * Revoke API token
 */
export const deleteV1TokensById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1TokensByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1TokensByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/tokens/{id}',
    ...options
});

/**
 * List user session templates
 */
export const getV1Templates = <ThrowOnError extends boolean = false>(options?: Options<GetV1TemplatesData, ThrowOnError>) => (options?.client ?? client).get<GetV1TemplatesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/templates',
    ...options
});

/**
 * Create session template
 */
export const postV1Templates = <ThrowOnError extends boolean = false>(options?: Options<PostV1TemplatesData, ThrowOnError>) => (options?.client ?? client).post<PostV1TemplatesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/templates',
    ...options
});

/**
 * Delete session template
 */
export const deleteV1TemplatesById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1TemplatesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1TemplatesByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/templates/{id}',
    ...options
});

/**
 * Update session template
 */
export const putV1TemplatesById = <ThrowOnError extends boolean = false>(options: Options<PutV1TemplatesByIdData, ThrowOnError>) => (options.client ?? client).put<PutV1TemplatesByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/templates/{id}',
    ...options
});

/**
 * List environment variables
 */
export const getV1EnvVars = <ThrowOnError extends boolean = false>(options?: Options<GetV1EnvVarsData, ThrowOnError>) => (options?.client ?? client).get<GetV1EnvVarsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/env-vars',
    ...options
});

/**
 * Create/update environment variable
 */
export const postV1EnvVars = <ThrowOnError extends boolean = false>(options?: Options<PostV1EnvVarsData, ThrowOnError>) => (options?.client ?? client).post<PostV1EnvVarsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/env-vars',
    ...options
});

/**
 * Delete environment variable
 */
export const deleteV1EnvVarsByName = <ThrowOnError extends boolean = false>(options: Options<DeleteV1EnvVarsByNameData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1EnvVarsByNameResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'termless_session',
            type: 'apiKey'
        }],
    url: '/v1/env-vars/{name}',
    ...options
});
