// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type GetReadyResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostAuthLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAuthOidcStartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/oidc/start';
};

export type GetAuthOidcStartResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostAuthTotpSetupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/totp/setup';
};

export type PostAuthTotpSetupResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostAuthTotpVerifyData = {
    body: {
        totpCode: string;
    };
    path?: never;
    query?: never;
    url: '/auth/totp/verify';
};

export type PostAuthTotpVerifyResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1SessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/sessions';
};

export type GetV1SessionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1SessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/sessions';
};

export type PostV1SessionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1SessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sessions/{id}';
};

export type DeleteV1SessionsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1WorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/workspaces';
};

export type GetV1WorkspacesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1WorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/workspaces';
};

export type PostV1WorkspacesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1WorkspacesByIdGitStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/workspaces/{id}/git-status';
};

export type GetV1WorkspacesByIdGitStatusResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1WorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/workspaces/{id}';
};

export type DeleteV1WorkspacesByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1AdminUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/admin/users';
};

export type GetV1AdminUsersResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1AdminUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/admin/users';
};

export type PostV1AdminUsersResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1AdminUsersByIdRoleData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/admin/users/{id}/role';
};

export type PutV1AdminUsersByIdRoleResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1AdminAuditLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/admin/audit-logs';
};

export type GetV1AdminAuditLogsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1AdminUsersByIdSessionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/admin/users/{id}/sessions';
};

export type DeleteV1AdminUsersByIdSessionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1WebhooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/webhooks';
};

export type GetV1WebhooksResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1WebhooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/webhooks';
};

export type PostV1WebhooksResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1WebhooksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/webhooks/{id}';
};

export type DeleteV1WebhooksByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1WebhooksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/webhooks/{id}';
};

export type PutV1WebhooksByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1TokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/tokens';
};

export type GetV1TokensResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1TokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/tokens';
};

export type PostV1TokensResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1TokensByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/tokens/{id}';
};

export type DeleteV1TokensByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1TemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/templates';
};

export type GetV1TemplatesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1TemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/templates';
};

export type PostV1TemplatesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1TemplatesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/templates/{id}';
};

export type DeleteV1TemplatesByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1TemplatesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/templates/{id}';
};

export type PutV1TemplatesByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1EnvVarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/env-vars';
};

export type GetV1EnvVarsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1EnvVarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/env-vars';
};

export type PostV1EnvVarsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1EnvVarsByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/v1/env-vars/{name}';
};

export type DeleteV1EnvVarsByNameResponses = {
    /**
     * Default Response
     */
    200: unknown;
};
