packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@biomejs/biome': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true
peerDependencyRules:
  allowAny:
    - eslint-plugin-react
    - eslint-plugin-jsx-a11y
    - eslint-plugin-vitest