import { baseConfig } from '@termless/eslint-config'
import { defineConfig } from 'eslint/config'

export default defineConfig([
  ...baseConfig,
  {
    name: 'termless/sdk-overrides',
    rules: {
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/consistent-type-exports': 'off',
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/naming-convention': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-enum-comparison': 'off',
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
      '@typescript-eslint/strict-boolean-expressions': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/prefer-string-replace-all': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/switch-exhaustiveness-check': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/only-throw-error': 'off',
      '@typescript-eslint/no-dynamic-delete': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-misused-spread': 'off',
      '@typescript-eslint/no-redundant-type-constituents': 'off',
      '@typescript-eslint/consistent-indexed-object-style': 'off',
      '@typescript-eslint/no-unnecessary-type-parameters': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'unicorn/filename-case': 'off',
      'unicorn/prevent-abbreviations': 'off',
      'unicorn/no-array-for-each': 'off',
      'unicorn/no-useless-switch-case': 'off',
      'unicorn/switch-case-braces': 'off',
      'unicorn/prefer-string-slice': 'off',
      'unicorn/explicit-length-check': 'off',
      'unicorn/no-negated-condition': 'off',
      'unicorn/no-useless-undefined': 'off',
      'unicorn/prefer-type-error': 'off',
      'unicorn/prefer-spread': 'off',
      'unicorn/prefer-string-replace-all': 'off',
      'unicorn/no-array-sort': 'off',
      'unicorn/numeric-separators-style': 'off',
      'sonarjs/cognitive-complexity': 'off',
      'sonarjs/function-return-type': 'off',
      'sonarjs/no-identical-functions': 'off',
      'sonarjs/different-types-comparison': 'off',
      'sonarjs/no-try-promise': 'off',
      'sonarjs/no-redundant-jump': 'off',
      'sonarjs/todo-tag': 'off',
      'import-x/order': 'off',
      'import-x/no-duplicates': 'off',
    },
  },
])